sudo: required

language: bash

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - IMAGE="alpine-fpm-php"
    - IMAGE_NAME="${DOCKER_USER}/${IMAGE}"

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1 
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

script:
  - find . -name "*.sh" -print0 | xargs -0 -r -n1 bash -n
  - bash ./build-images.sh