sudo: required
language: bash

branches:
  only:
  - master

services:
  - docker

env:
  global:
    - IMAGE="alpine-fpm-php""
    - IMAGE_NAME="${DOCKER_USER}/${IMAGE}"

before_script:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"

script:
  - bash ./build_changed.sh